# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
    ]
